#thank you to networkchuck on youtube

Microsoft Windows [Version 10.0.19044.1766]
(c) Microsoft Corporation. All rights reserved.

C:\Users\kdurj>ssh root@170.187.141.227
root@170.187.141.227's password:
Welcome to Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-43-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Aug 10 01:09:27 AM UTC 2022

  System load:           0.0
  Usage of /:            10.6% of 24.04GB
  Memory usage:          18%
  Swap usage:            0%
  Processes:             97
  Users logged in:       1
  IPv4 address for eth0: 170.187.141.227
  IPv6 address for eth0: 2600:3c02::f03c:93ff:feb4:bdf


1 update can be applied immediately.
1 of these updates is a standard security update.
To see these additional updates run: apt list --upgradable


Last login: Wed Aug 10 00:23:16 2022 from 108.189.60.154
root@localhost:~# ls
ransomware
root@localhost:~# mkdir
mkdir: missing operand
Try 'mkdir --help' for more information.
root@localhost:~# mkdir test
root@localhost:~# ls
ransomware  test
root@localhost:~# echo file.txt
file.txt
root@localhost:~#  echo this is a file file.txt
this is a file file.txt
root@localhost:~# ls
ransomware  test
root@localhost:~# cd test
root@localhost:~/test# ls
root@localhost:~/test# echo this is a file file.txt
this is a file file.txt
root@localhost:~/test# ls
root@localhost:~/test# python.gu
python.gu: command not found
root@localhost:~/test# cd ransomware
-bash: cd: ransomware: No such file or directory
root@localhost:~/test# cd../
-bash: cd../: No such file or directory
root@localhost:~/test# cd..\
> cd ransomware
cd..cd: command not found
root@localhost:~/test# cd.?
cd.?: command not found
root@localhost:~/test# cd./
-bash: cd./: No such file or directory
root@localhost:~/test# cd
root@localhost:~# ransomware
ransomware: command not found
root@localhost:~# mkdir ransomware
mkdir: cannot create directory ‘ransomware’: File exists
root@localhost:~# ransomware
ransomware: command not found
root@localhost:~# cd ransomware/
root@localhost:~/ransomware# ls
file2.txt  file.txt  Hey.txt  pleasedonthurtme.txt  test  thekey.key  voldemort.py
root@localhost:~/ransomware# nano voldemore.py




root@localhost:~/ransomware# python3 voldemort.py
['.voldemort.py.swp', 'pleasedonthurtme.txt', 'Hey.txt', 'file.txt', 'file2.txt']
Traceback (most recent call last):
  File "/root/ransomware/voldemort.py", line 30, in <module>
    with open(files, "wb") as thefile:
TypeError: expected str, bytes or os.PathLike object, not list
root@localhost:~/ransomware# nano voldemort.py
root@localhost:~/ransomware# nano voldemort.py
root@localhost:~/ransomware# python3 voldemort.py
['pleasedonthurtme.txt', 'Hey.txt', 'file.txt', 'file2.txt']
root@localhost:~/ransomware# ls
file2.txt  file.txt  Hey.txt  pleasedonthurtme.txt  test  thekey.key  voldemort.py
root@localhost:~/ransomware# cat file.txt
gAAAAABi8weepZTFhMb_yygL-_geS2RPd0PfsJgqyGk5uXBHjgaxpFKnsm7dtB9rqWU19PNbkvrIzOBWkDKedZJuh4Lun2cdKQ==root@localhost:~/ransomware# cat thekey.key
7lakTMOmSL3SsYWDVFoQkiRw6Xb0IE0ZX-gTMesYZI8=root@localhost:~/ransomware#
root@localhost:~/ransomware# cp voldemort.py decrypt.py
root@localhost:~/ransomware# nano decrypt.py
root@localhost:~/ransomware# cat file.txt
gAAAAABi8weepZTFhMb_yygL-_geS2RPd0PfsJgqyGk5uXBHjgaxpFKnsm7dtB9rqWU19PNbkvrIzOBWkDKedZJuh4Lun2cdKQ==root@localhost:~/ransomware# python3 decrypt.py
['pleasedonthurtme.txt', 'Hey.txt', 'file.txt', 'decrypt.py', 'file2.txt']
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 102, in _get_unverified_token_data
    data = base64.urlsafe_b64decode(token)
  File "/usr/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (377) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ransomware/decrypt.py", line 31, in <module>
    contents_decrypted = Fernet(secretkey).decrypt(contents)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 75, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 104, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
root@localhost:~/ransomware# nano decrypt.py
root@localhost:~/ransomware# root@localhost:~/ransomware# python3 decrypt.py
['pleasedonthurtme.txt', 'Hey.txt', 'file.txt', 'decrypt.py', 'file2.txt']
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 102, in _get_unverified_token_data
    data = base64.urlsafe_b64decode(token)
  File "/usr/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ransomware/decrypt.py", line 31, in <module>
    contents_decrypted = Fernet(secretkey).decrypt(contents)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 75, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 104, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
root@localhost:~/ransomware# python3 voldemort.py
['pleasedonthurtme.txt', 'Hey.txt', 'file.txt', 'decrypt.py', 'file2.txt']
root@localhost:~/ransomware# python3 decrypt.py
  File "/root/ransomware/decrypt.py", line 1
    gAAAAABi8wnv18U5Y5EwLVJJzKX_s7JL9gCQ0qWCV1v3QrS9QefALLBdJltDMzRnVLRvRlPLw3JbKlCrVPIi5Vtd-PCAwtI74Pjb7CsCUzI-PTxlUkk_kesDRFfH9aaRbbj37jvmi6fLHKaCAb2w9UJ-t38zqfAYknMiKxQjYNt0x01-Gg8xPEXQwpyYPo5szsif_Y4Mey-TFRDRzTO72-gdW_BDoiAXrSQ4tK6uHcL3AwnbA8OK1ZyZ_bgMvM46tyW7qS3ftXuYr34ZDXhykDzABPTkTAmBjms5AEn3b2SzjIGR10PtzCIoElBXvxIqmPtKPGnFQ7-i-5NEXDmoSciCjORXUuqNQ_03zNMccOf94h-6o7rjO_SE04GmvWDZEyF2yw3DpjdsNIgxTzLh7WUR5eMFpHQLMJKhfow7Jr0iPdeKcaYZEVN8F5HY1GaRtkO1nQqdWE8Jb_026jsPy9AwTNctq3jF7QxnlTL8hK7H4R59zAHnISRJhk8vE2avWZUhl2BEN93PjWgasoWwOkLm7AU46hTWyqXL9Vkc3aee1if8XM0SlkO8vtoAuWr4aanFzeHS5hZfCBu_wNxu4zfHOixL5TNdozrOvaRwmIZ0apHFBsBMb5RxaifcUZG2xv37x4v9tIUks6tt67fuVyPwlLbn5igNlIYHqXWhdl-RmR7XYFbR6g5qcXnnSimQ6sobYzdA9grayivxoI8a_lt7GuHq7eGOih4BznXk7u-cfuGHVJr-i4K0-EQFlJWqygA4RrHhBX4IV3RwPcXw0fki9EVgXEq4Hd1lVXtUxQUwWQ3TrHSL2sw=
                                                                                                                                                                                                                                                                                                                                                 ^
SyntaxError: invalid decimal literal
root@localhost:~/ransomware# python3 decrypt.py
  File "/root/ransomware/decrypt.py", line 1
    gAAAAABi8wnv18U5Y5EwLVJJzKX_s7JL9gCQ0qWCV1v3QrS9QefALLBdJltDMzRnVLRvRlPLw3JbKlCrVPIi5Vtd-PCAwtI74Pjb7CsCUzI-PTxlUkk_kesDRFfH9aaRbbj37jvmi6fLHKaCAb2w9UJ-t38zqfAYknMiKxQjYNt0x01-Gg8xPEXQwpyYPo5szsif_Y4Mey-TFRDRzTO72-gdW_BDoiAXrSQ4tK6uHcL3AwnbA8OK1ZyZ_bgMvM46tyW7qS3ftXuYr34ZDXhykDzABPTkTAmBjms5AEn3b2SzjIGR10PtzCIoElBXvxIqmPtKPGnFQ7-i-5NEXDmoSciCjORXUuqNQ_03zNMccOf94h-6o7rjO_SE04GmvWDZEyF2yw3DpjdsNIgxTzLh7WUR5eMFpHQLMJKhfow7Jr0iPdeKcaYZEVN8F5HY1GaRtkO1nQqdWE8Jb_026jsPy9AwTNctq3jF7QxnlTL8hK7H4R59zAHnISRJhk8vE2avWZUhl2BEN93PjWgasoWwOkLm7AU46hTWyqXL9Vkc3aee1if8XM0SlkO8vtoAuWr4aanFzeHS5hZfCBu_wNxu4zfHOixL5TNdozrOvaRwmIZ0apHFBsBMb5RxaifcUZG2xv37x4v9tIUks6tt67fuVyPwlLbn5igNlIYHqXWhdl-RmR7XYFbR6g5qcXnnSimQ6sobYzdA9grayivxoI8a_lt7GuHq7eGOih4BznXk7u-cfuGHVJr-i4K0-EQFlJWqygA4RrHhBX4IV3RwPcXw0fki9EVgXEq4Hd1lVXtUxQUwWQ3TrHSL2sw=
                                                                                                                                                                                                                                                                                                                                                 ^
SyntaxError: invalid decimal literal
root@localhost:~/ransomware# nano decrypt.py
root@localhost:~/ransomware# root@localhost:~/ransomware#
root@localhost:~/ransomware# cp voldemort.py decrypt.py
root@localhost:~/ransomware# cp voldemort.py decryptt.py
root@localhost:~/ransomware# nano decryptt.py
root@localhost:~/ransomware# root@localhost:~/ransomware#
root@localhost:~/ransomware# cat file.txt
gAAAAABi8wnv8VAI8ZTPM8_yCsO1cF8cN6sj859GacTQofeJzLTK72r12O87Xpb8Riqv7T62RFVeYl9Cgn0Sb0f5MQfOjotQSg==root@localhost:~/ransomware# python3 decryptt.py
['pleasedonthurtme.txt', 'Hey.txt', 'file.txt', 'decrypt.py', 'file2.txt']
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 102, in _get_unverified_token_data
    data = base64.urlsafe_b64decode(token)
  File "/usr/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ransomware/decryptt.py", line 26, in <module>
    contents_decrypted = Fernet(secretkey).decrypt(contents)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 75, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 104, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
root@localhost:~/ransomware# nano decryptt.py
root@localhost:~/ransomware# update fernet
Command 'update' not found, did you mean:
  command 'zupdate' from deb zutils (1.11-1)
  command 'lupdate' from deb qtchooser (66-2build1)
  command 'xupdate' from deb libxml-xupdate-libxml-perl (0.6.0-3.1)
  command 'uupdate' from deb devscripts (2.22.1ubuntu1)
  command 'pupdate' from deb pbuilder-scripts (22)
Try: apt install <deb name>
root@localhost:~/ransomware# ls
decrypt.py  decryptt.py  file2.txt  file.txt  Hey.txt  pleasedonthurtme.txt  test  thekey.key  voldemort.py
root@localhost:~/ransomware# cat file.txt
This is a file
root@localhost:~/ransomware# python3 voldemort.py
['decryptt.py', 'pleasedonthurtme.txt', 'Hey.txt', 'file.txt', 'decrypt.py', 'file2.txt']
root@localhost:~/ransomware# cat hey.txt
cat: hey.txt: No such file or directory
root@localhost:~/ransomware# cat Hey.txt
gAAAAABi8w0V-TrGTf8S_gCZXkkvrVBf_L8Wda_T-uVxiP7j02xbqrL6NpuG1tdOqXOiX2Y-rO7BtQQZycxC7mLG-yxmrD-qMg==root@localhost:~/ransomware# python3 decryptt.py
  File "/root/ransomware/decryptt.py", line 1
    gAAAAABi8w0VAPPUSAoMiS5nhZm6eu2QQPI3zCrHBtxV61AG6yCGQHlklPCG4mQvLjcM3fwFFgRmTvScbP80qCcHx1YILRplhixIyk7i0hyWG64ba-zvGwt0Onc5gMpUurkhDYNUx7JmK8axW4q1AF8aa8kZghPQdrPjWWMXkhZC8QgliH8P3ttg-vbL2bzlDiM3JZl_e_gA6SLjH-iMk8krmrmQ_A4lWrpndWLkU3sN5J_FGFiQdPBxIwrobzOx-n2MxZVB_zg7fRIY3HWkamKobYCz0HVs2wr_zGFebzT7h-UAtdBdHSnRBf9rYRKsCQUXWsWL4IoyiPfalMA8Jq9aXGvtkyJz2Z8iZmU1GGpKgF-vTbFxwbqof7V5-IXJUfE23SYZIV3E-iQNK80sMhNYB8tMIohQRAyJJ4QYQv3Hz7kAS3lC68Hgc48bw8qK6ltvm7LZOhFNsEXNzohoLs65c6I8167I-65brzNhYBqwV9N5KHJ2AZ1xXeG0PYBeKHrtRdnAOK8Q0qR9pzGeNFIEwbUJUWjWIDYObbNEmse5wiNG8UJkQFuuu0heEj0WyKbeKXz_ouwVCQKgmye-QdN-DWz7M6XrP5r59UJbA8Fwt6Ad2JNw36JeK_J1XgEcICuXHMqL_qM-K2AjR7FLboa0XOSm3rkR8M8-Vy5b6jDI9mjp5rTsWXDmit43yBwBMBYDJxiCWo8XPNXItaOWonrrjnPHqBHnjSNpiRC38x_qaVMD8fxcFugKBnX9V-Js-XuM7_FYHhrC3Jg8bs6aRQVEIoRVMc7RH4mBj4yu9PexCrUQouC5zY8=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^
SyntaxError: invalid decimal literal
root@localhost:~/ransomware# ls
decrypt.py  decryptt.py  file2.txt  file.txt  Hey.txt  pleasedonthurtme.txt  test  thekey.key  voldemort.py
root@localhost:~/ransomware# cat file.txt
gAAAAABi8w0VHhFGKeOoQ9ui8Do-GhmxQokg3zuutgPDY2zT9ogo2MTJEqlFmypzdVswXcJ1Pcn28tX3eZ64kVlKcolN9S-BhA==root@localhost:~/ransomware# python3 decryptt.py
  File "/root/ransomware/decryptt.py", line 1
    gAAAAABi8w0VAPPUSAoMiS5nhZm6eu2QQPI3zCrHBtxV61AG6yCGQHlklPCG4mQvLjcM3fwFFgRmTvScbP80qCcHx1YILRplhixIyk7i0hyWG64ba-zvGwt0Onc5gMpUurkhDYNUx7JmK8axW4q1AF8aa8kZghPQdrPjWWMXkhZC8QgliH8P3ttg-vbL2bzlDiM3JZl_e_gA6SLjH-iMk8krmrmQ_A4lWrpndWLkU3sN5J_FGFiQdPBxIwrobzOx-n2MxZVB_zg7fRIY3HWkamKobYCz0HVs2wr_zGFebzT7h-UAtdBdHSnRBf9rYRKsCQUXWsWL4IoyiPfalMA8Jq9aXGvtkyJz2Z8iZmU1GGpKgF-vTbFxwbqof7V5-IXJUfE23SYZIV3E-iQNK80sMhNYB8tMIohQRAyJJ4QYQv3Hz7kAS3lC68Hgc48bw8qK6ltvm7LZOhFNsEXNzohoLs65c6I8167I-65brzNhYBqwV9N5KHJ2AZ1xXeG0PYBeKHrtRdnAOK8Q0qR9pzGeNFIEwbUJUWjWIDYObbNEmse5wiNG8UJkQFuuu0heEj0WyKbeKXz_ouwVCQKgmye-QdN-DWz7M6XrP5r59UJbA8Fwt6Ad2JNw36JeK_J1XgEcICuXHMqL_qM-K2AjR7FLboa0XOSm3rkR8M8-Vy5b6jDI9mjp5rTsWXDmit43yBwBMBYDJxiCWo8XPNXItaOWonrrjnPHqBHnjSNpiRC38x_qaVMD8fxcFugKBnX9V-Js-XuM7_FYHhrC3Jg8bs6aRQVEIoRVMc7RH4mBj4yu9PexCrUQouC5zY8=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^
SyntaxError: invalid decimal literal
root@localhost:~/ransomware# ls
decrypt.py  decryptt.py  file2.txt  file.txt  Hey.txt  pleasedonthurtme.txt  test  thekey.key  voldemort.py
root@localhost:~/ransomware# python3 decryptt.py
  File "/root/ransomware/decryptt.py", line 1
    gAAAAABi8w0VAPPUSAoMiS5nhZm6eu2QQPI3zCrHBtxV61AG6yCGQHlklPCG4mQvLjcM3fwFFgRmTvScbP80qCcHx1YILRplhixIyk7i0hyWG64ba-zvGwt0Onc5gMpUurkhDYNUx7JmK8axW4q1AF8aa8kZghPQdrPjWWMXkhZC8QgliH8P3ttg-vbL2bzlDiM3JZl_e_gA6SLjH-iMk8krmrmQ_A4lWrpndWLkU3sN5J_FGFiQdPBxIwrobzOx-n2MxZVB_zg7fRIY3HWkamKobYCz0HVs2wr_zGFebzT7h-UAtdBdHSnRBf9rYRKsCQUXWsWL4IoyiPfalMA8Jq9aXGvtkyJz2Z8iZmU1GGpKgF-vTbFxwbqof7V5-IXJUfE23SYZIV3E-iQNK80sMhNYB8tMIohQRAyJJ4QYQv3Hz7kAS3lC68Hgc48bw8qK6ltvm7LZOhFNsEXNzohoLs65c6I8167I-65brzNhYBqwV9N5KHJ2AZ1xXeG0PYBeKHrtRdnAOK8Q0qR9pzGeNFIEwbUJUWjWIDYObbNEmse5wiNG8UJkQFuuu0heEj0WyKbeKXz_ouwVCQKgmye-QdN-DWz7M6XrP5r59UJbA8Fwt6Ad2JNw36JeK_J1XgEcICuXHMqL_qM-K2AjR7FLboa0XOSm3rkR8M8-Vy5b6jDI9mjp5rTsWXDmit43yBwBMBYDJxiCWo8XPNXItaOWonrrjnPHqBHnjSNpiRC38x_qaVMD8fxcFugKBnX9V-Js-XuM7_FYHhrC3Jg8bs6aRQVEIoRVMc7RH4mBj4yu9PexCrUQouC5zY8=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ^
SyntaxError: invalid decimal literal
root@localhost:~/ransomware# ls
decrypt.py  decryptt.py  file2.txt  file.txt  Hey.txt  pleasedonthurtme.txt  test  thekey.key  voldemort.py
root@localhost:~/ransomware# cat file.txt
gAAAAABi8w0VHhFGKeOoQ9ui8Do-GhmxQokg3zuutgPDY2zT9ogo2MTJEqlFmypzdVswXcJ1Pcn28tX3eZ64kVlKcolN9S-BhA==root@localhost:~/ransomware# nano decryptt.py
root@localhost:~/ransomware# nano decryptt.py
root@localhost:~/ransomware#
root@localhost:~/ransomware#
root@localhost:~/ransomware# nano decryptt.py
root@localhost:~/ransomware# nano decrypt.py
root@localhost:~/ransomware# cp voldemort.py decrypt.py
root@localhost:~/ransomware# nano decrypt.py
root@localhost:~/ransomware#
root@localhost:~/ransomware# cat file.txt
gAAAAABi8w0VHhFGKeOoQ9ui8Do-GhmxQokg3zuutgPDY2zT9ogo2MTJEqlFmypzdVswXcJ1Pcn28tX3eZ64kVlKcolN9S-BhA==root@localhost:~/ransomware#
root@localhost:~/ransomware# python3 decrypt.py
['decryptt.py', 'pleasedonthurtme.txt', 'Hey.txt', 'file.txt', 'file2.txt']
root@localhost:~/ransomware# cat file.txt
This is a file
root@localhost:~/ransomware#


